theme = "native"
icons = "awesome5"


[[block]]
block = "music"
player = "spotify"
format = "{artist} - {title} "
max_width = 50
dynamic_width = true

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "time"
interval = 60
format = "%d.%m.%Y %R"
