# bind r to reload config
bind r source-file ~/.tmux.conf
set -s escape-time 1

set -g status-justify centre
set -g monitor-activity on
set -g visual-activity on
set -g automatic-rename on

set -g default-terminal "screen-256color"

# start numbering at 1
set -g base-index 1
set -g pane-base-index 1

# vim like copy 
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection 
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection c"

# statusbar colors
set-option -g status-bg colour235 #base02
set-option -g status-fg colour136 #yellow
set -g status on

# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange

# clock
set-window-option -g clock-mode-colour colour64 #green

#customize left and right statusbar
set -g status-left "#h:[#S]"
set -g status-left-length 50
set -g status-right "%H:%M %d-%h-%Y"
set -g status-right-length 50

# enable mouse
set -g mouse on

# open split in same dir as original
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
